version: '3.7'

services:
    linkedu_service:
        build: .
        volumes:
            - .:/app/
            - static_files:/app/static_files

        container_name: linkedu_service
        expose:
            - 8000
        env_file:
            - ./LinkedU/.env
        networks:
            - linkedu-net
        restart: always
        depends_on:
            - linkedu_db_service

    linkedu_db_service:
        image: postgres
        restart: always
        volumes:
            - linkedu:/var/lib/postgresql/data
        networks:
            - linkedu-net
        container_name: linkedu_db
        env_file:
            - ./LinkedU/.env
        ports:
            - 5432:5432

    nginx:
        build: ./nginx
        volumes:
            - static_files:/app/static_files
        ports:
            - "8000:80"
        networks:
            - linkedu-net

        depends_on:
            - linkedu_service

volumes:
    static_files:
    linkedu:


networks:
    linkedu-net:


